name: UX目安箱 📬
description: 気になったUXを投稿しよう！
body:
  - type: textarea
    id: capture
    attributes:
      label: スクリーンショット or 動画
      description: まずは気になるUIのスクリーンショット or 動画をはろう！
      placeholder: ショートカット（Win：win + shift + S, Mac：shift + command + 4）
    validations:
      required: true
  - type: textarea
    id: explanation
    attributes:
      label: 解説
      placeholder: 気になったことをおしえてください！
    validations:
      required: true
  - type: textarea
    id: do
    attributes:
      label: 改善案
      placeholder: どうすれば良くなるとおもいますか？（ざっくりでOK）
  - type: textarea
    id: supplement
    attributes:
      label: 補足
      placeholder: その他語りたいことがあればどうぞ！
